spring:
  cache:
    cache-names: bookings, customers, flights
    caffeine:
      spec: maximumSize=500, expireAfterAccess=30m
  application:
    name: booking-service
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  secret: gh1Zfwt0nJQL3TENb8JJHoDwJ624KwYNBCaR11z5GMQ=
  authority: app-auth
  noFilterPaths: /v3/, /swagger-ui/

server:
  port: 8209
  error:
    include-message: always

customer-service:
  auth:
    username: user
    password: the_cake

notification-service:
  comms:
    routing-key: booking.created





