spring:
  cache:
    cache-names: bookings
    caffeine:
      spec: maximumSize=500, expireAfterAccess=30m
  application:
    name: booking-service
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  springdoc:
    swagger-ui:
      path=/swagger-ui.html


server:
  port: 8209
  error:
    include-message: always


