//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.09 at 11:06:07 AM SAST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://entelect.training/incubator/spring-loyalty-service", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package entelect.training.incubator.spring.booking.rewards.stub;
